// Collections {}[]
module.exports.diff = require("just-diff").diff;
module.exports.diffApply = require("just-diff-apply").diffApply;
module.exports.compare = require("just-compare");
module.exports.clone = require("just-clone");
module.exports.pluckIt = require("just-pluck-it");
module.exports.flush = require("just-flush");

// Objects {}
module.exports.extend = require("just-extend");
module.exports.merge = require("just-merge");
module.exports.values = require("just-values");
module.exports.entries = require("just-entries");
module.exports.pick = require("just-pick");
module.exports.omit = require("just-omit");
module.exports.filterObject = require("just-filter-object");
module.exports.mapObject = require("just-map-object");
module.exports.mapValues = require("just-map-values");
module.exports.mapKeys = require("just-map-keys");
module.exports.reduceObject = require("just-reduce-object");
module.exports.isEmpty = require("just-is-empty");
module.exports.isCircular = require("just-is-circular");
module.exports.isPrimitive = require("just-is-primitive");
module.exports.safeGet = require("just-safe-get");
module.exports.safeSet = require("just-safe-set");
module.exports.typeOf = require("just-typeof");
module.exports.flipObject = require("just-flip-object");

// Arrays []
module.exports.cartesianProduct = require("just-cartesian-product");
module.exports.unique = require("just-unique");
module.exports.flattenIt = require("just-flatten-it");
module.exports.index = require("just-index");
module.exports.insert = require("just-insert");
module.exports.intersect = require("just-intersect");
module.exports.compact = require("just-compact");
module.exports.last = require("just-last");
module.exports.tail = require("just-tail");
module.exports.random = require("just-random");
module.exports.shuffle = require("just-shuffle");
module.exports.split = require("just-split");
module.exports.splitAt = require("just-split-at");
module.exports.partition = require("just-partition");
module.exports.permutations = require("just-permutations");
module.exports.range = require("just-range");
module.exports.remove = require("just-remove");
module.exports.union = require("just-union");
module.exports.zipIt = require("just-zip-it");
module.exports.groupBy = require("just-group-by");

// Statistics Σ
module.exports.mean = require("just-mean");
module.exports.median = require("just-median");
module.exports.memoize = require("just-memoize");
module.exports.mode = require("just-mode");
module.exports.percentile = require("just-percentile");
module.exports.variance = require("just-variance");
module.exports.stdev = require("just-stdev");
module.exports.skewness = require("just-skewness");

// Strings ""
module.exports.template = require("just-template");
module.exports.truncate = require("just-truncate");
module.exports.prune = require("just-prune");
module.exports.squash = require("just-squash");
module.exports.leftPad = require("just-left-pad");
module.exports.rightPad = require("just-right-pad");
module.exports.camelCase = require("just-camel-case");
module.exports.kebabCase = require("just-kebab-case");
module.exports.snakeCase = require("just-snake-case");
module.exports.pascalCase = require("just-pascal-case");
module.exports.capitalize = require("just-capitalize");
module.exports.replaceAll = require("just-replace-all");

// Numbers +-
module.exports.clamp = require("just-clamp");
module.exports.isPrime = require("just-is-prime");
module.exports.modulo = require("just-modulo");

// Functions =>
module.exports.compose = require("just-compose");
module.exports.curryIt = require("just-curry-it");
module.exports.demethodize = require("just-demethodize");
module.exports.flip = require("just-flip");
module.exports.partialIt = require("just-partial-it");
module.exports.debounceIt = require("just-debounce-it");
module.exports.throttle = require("just-throttle");
module.exports.once = require("just-once");
